# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'OpenCV', '~> 2.4'

target 'BouncerBuddy' do

end

target 'BouncerBuddyTests' do

end

target 'BouncerBuddyUITests' do

end

